apiVersion: v1
kind: PersistentVolume
metadata:
  name: spark-master-pv
  namespace: spark
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/spark-master

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-master-pvc
  namespace: spark
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: spark-worker-pv
  namespace: spark
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/spark-worker

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-worker-pvc
  namespace: spark
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
