apiVersion: v1
kind: Service
metadata:
  name: spark-master
  namespace: spark
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
  selector:
    app: spark-master

---
apiVersion: v1
kind: Service
metadata:
  name: spark-worker
  namespace: spark
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app: spark-worker
